[build]
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_API_URL = "https://taxi-express.up.railway.app/api"

[dev]
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
